// GENERATED CODE - Hive Type Adapter for Patient Model
// This file would normally be generated by build_runner
// Run: flutter pub run build_runner build

part of 'patient_model.dart';

// ignore_for_file: type=lint

class PatientAdapter extends TypeAdapter<Patient> {
  @override
  final int typeId = 0;

  @override
  Patient read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Patient(
      id: fields[0] as String,
      name: fields[1] as String,
      age: fields[2] as int,
      gender: fields[3] as String,
      village: fields[4] as String,
      phoneNumber: fields[5] as String,
      lastVisit: fields[6] as DateTime?,
      nextVisit: fields[7] as DateTime?,
      ancVisit: fields[8] as DateTime?,
      syncStatus: fields[9] as String,
      createdAt: fields[10] as DateTime,
      updatedAt: fields[11] as DateTime,
      abhaId: fields[12] as String?,
      isPriority: fields[13] as bool,
      riskLevel: fields[14] as String?,
      vitals: fields[15] as Map<String, dynamic>?,
      conditions: (fields[16] as List?)?.cast<String>(),
      assignedWorker: fields[17] as String?,
      version: fields[18] as int,
    );
  }

  @override
  void write(BinaryWriter writer, Patient obj) {
    writer
      ..writeByte(19)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.name)
      ..writeByte(2)
      ..write(obj.age)
      ..writeByte(3)
      ..write(obj.gender)
      ..writeByte(4)
      ..write(obj.village)
      ..writeByte(5)
      ..write(obj.phoneNumber)
      ..writeByte(6)
      ..write(obj.lastVisit)
      ..writeByte(7)
      ..write(obj.nextVisit)
      ..writeByte(8)
      ..write(obj.ancVisit)
      ..writeByte(9)
      ..write(obj.syncStatus)
      ..writeByte(10)
      ..write(obj.createdAt)
      ..writeByte(11)
      ..write(obj.updatedAt)
      ..writeByte(12)
      ..write(obj.abhaId)
      ..writeByte(13)
      ..write(obj.isPriority)
      ..writeByte(14)
      ..write(obj.riskLevel)
      ..writeByte(15)
      ..write(obj.vitals)
      ..writeByte(16)
      ..write(obj.conditions)
      ..writeByte(17)
      ..write(obj.assignedWorker)
      ..writeByte(18)
      ..write(obj.version);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PatientAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
