// GENERATED CODE - Hive Type Adapter for Worker Model
// This file would normally be generated by build_runner
// Run: flutter pub run build_runner build

part of 'worker_model.dart';

// ignore_for_file: type=lint

class WorkerAdapter extends TypeAdapter<Worker> {
  @override
  final int typeId = 1;

  @override
  Worker read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Worker(
      workerId: fields[0] as String,
      name: fields[1] as String,
      village: fields[2] as String,
      role: fields[3] as String,
      pin: fields[4] as String,
      createdAt: fields[5] as DateTime,
      phoneNumber: fields[6] as String?,
      isActive: fields[7] as bool,
    );
  }

  @override
  void write(BinaryWriter writer, Worker obj) {
    writer
      ..writeByte(8)
      ..writeByte(0)
      ..write(obj.workerId)
      ..writeByte(1)
      ..write(obj.name)
      ..writeByte(2)
      ..write(obj.village)
      ..writeByte(3)
      ..write(obj.role)
      ..writeByte(4)
      ..write(obj.pin)
      ..writeByte(5)
      ..write(obj.createdAt)
      ..writeByte(6)
      ..write(obj.phoneNumber)
      ..writeByte(7)
      ..write(obj.isActive);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkerAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
